name: Test GHA Triggers

on:
  push:
    paths:
      - '**'
      - '!.github/**'
    branches:
      - master
    tags:
      - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: "Show data"
        run: |
          echo ${{ github.ref }}
