name: Test GHA Triggers

on:
  push:
    paths:
      - '**'
      - '!.github/**'
    branches:
      - master
    tags:
      - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: "Show data"
        run: |
          echo ${{ github.ref }}
          echo ${{ github.event_name }}
          echo ${{ startsWith(github.ref, 'refs/tags/v') }}
          echo ${{ !startsWith(github.ref, 'refs/tags/v') }}
          echo ${{ ( github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') ) }}
